# Site settings
title: ShaoZi's Blog
SEOTitle: 陈勺子的博客 | ShaoZi's Blog
header-img: img/post-bg-desk.jpg
email: chenyue21@jd.com
description: "Hello World."
keyword: "1，2，3，4"
url: "chen94yue.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/chen94yue/chen94yue.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Hello World!"
sidebar-avatar: /img/ShaoZi.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
weibo_username:     陈DB的日常
# zhihu_username:     qiubaiying
github_username:    Chen94yue
# facebook_username:  baiying.qiu.7
jianshu_username:   bdb87b292706
#twitter_username:   qiubaiying




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 7d71de0a29dde0646487                            #生成的clientID
  clientSecret: 3e0b8295ff12dc017e0d5a39a8a91e9ff8158b06    #生成的clientSecret
  repo: chen94yue.github.io    #仓库名称
  owner: Chen94yue    #github用户名
  admin: Chen94yue
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: c07acc7933f808aea1f7339ee5e0a935

# Google Analytics
ga_track_id: 'UA-135042923-1'            # Format: UA-xxxxxx-xx
ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "shaozi_ss",
        href: "https://www.jianshu.com/u/bdb87b292706"
    }
]
